# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DoubleOSeven Codes
email:
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my 180 code challenges page! Feel free to look around.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://DoubleOSeven.github.io" # the base hostname & protocol for your site
twitter_username: 007_78
github_username:  DoubleOSeven
future: true

# Build settings
markdown: kramdown
highlighter: rouge
